// <auto-generated />
using System;
using APICatalogo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APICatalogo.Migrations
{
  [DbContext(typeof(AppDbContext))]
  [Migration("20230128010547_CriacaoDoBanco")]
  partial class CriacaoDoBanco
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "7.0.2")
          .HasAnnotation("Relational:MaxIdentifierLength", 64);

      modelBuilder.Entity("APICatalogo.Domain.Categoria", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<string>("ImgagemUrl")
                      .HasColumnType("longtext");

            b.Property<string>("Nome")
                      .HasColumnType("longtext");

            b.HasKey("Id");

            b.ToTable("Categorias");
          });

      modelBuilder.Entity("APICatalogo.Domain.Produto", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<int>("CategoriaId")
                      .HasColumnType("int");

            b.Property<DateTime>("DataCadastro")
                      .HasColumnType("datetime(6)");

            b.Property<string>("Descricao")
                      .HasColumnType("longtext");

            b.Property<float>("Estoque")
                      .HasColumnType("float");

            b.Property<string>("ImagemUrl")
                      .HasColumnType("longtext");

            b.Property<string>("Nome")
                      .HasColumnType("longtext");

            b.Property<decimal>("Preco")
                      .HasColumnType("decimal(65,30)");

            b.HasKey("Id");

            b.HasIndex("CategoriaId");

            b.ToTable("Produtos");
          });

      modelBuilder.Entity("APICatalogo.Domain.Produto", b =>
          {
            b.HasOne("APICatalogo.Domain.Categoria", "Categoria")
                      .WithMany("Produtos")
                      .HasForeignKey("CategoriaId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("Categoria");
          });

      modelBuilder.Entity("APICatalogo.Domain.Categoria", b =>
          {
            b.Navigation("Produtos");
          });
#pragma warning restore 612, 618
    }
  }
}
